In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
df  = pd.read_csv("data/silver/dados_limpos.csv")
df.head(5)

,CODIGO_CLIENTE,UF,IDADE,ESCOLARIDADE,ESTADO_CIVIL,QT_FILHOS,CASA_PROPRIA,QT_IMOVEIS,VL_IMOVEIS,OUTRA_RENDA,...,TEMPO_ULTIMO_EMPREGO_MESES,TRABALHANDO_ATUALMENTE,ULTIMO_SALARIO,QT_CARROS,VALOR_TABELA_CARROS,SCORE,DATA_UPLOAD,ARQUIVO_FONTE,RENDA_TOTAL,DATA_TRATAMENTO
0,1,SP,19,Superior Cursando,Solteiro,0,False,0,0.0,False,...,8,True,1800.0,0,0.0,12,2025-11-03 02:52:22.878953,DADOS_CREDITO.XLSX,1800.0,2025-11-03 03:22:00.033018
1,2,MG,23,Superior Completo,Solteiro,1,False,0,0.0,False,...,9,False,4800.0,1,50000.0,18,2025-11-03 02:52:22.878953,DADOS_CREDITO.XLSX,4800.0,2025-11-03 03:22:00.033018
2,3,SC,25,Segundo Grau Completo,Casado,0,True,1,220000.0,False,...,18,True,2200.0,2,30000.0,23,2025-11-03 02:52:22.878953,DADOS_CREDITO.XLSX,2200.0,2025-11-03 03:22:00.033018
3,4,PR,27,Superior Cursando,Casado,1,True,0,0.0,False,...,22,False,3900.0,0,0.0,28,2025-11-03 02:52:22.878953,DADOS_CREDITO.XLSX,3900.0,2025-11-03 03:22:00.033018
4,5,RJ,28,Superior Completo,Divorciado,2,False,1,370000.0,False,...,30,True,6100.0,1,35000.0,34,2025-11-03 02:52:22.878953,DADOS_CREDITO.XLSX,6100.0,2025-11-03 03:22:00.033018

In [3]:
target = df["SCORE"]
df = df.drop(columns=['DATA_UPLOAD', 'ARQUIVO_FONTE', 'DATA_TRATAMENTO'])

In [4]:
preditoras = df.drop(columns=['SCORE'])

preditoras.head()

,CODIGO_CLIENTE,UF,IDADE,ESCOLARIDADE,ESTADO_CIVIL,QT_FILHOS,CASA_PROPRIA,QT_IMOVEIS,VL_IMOVEIS,OUTRA_RENDA,OUTRA_RENDA_VALOR,TEMPO_ULTIMO_EMPREGO_MESES,TRABALHANDO_ATUALMENTE,ULTIMO_SALARIO,QT_CARROS,VALOR_TABELA_CARROS,RENDA_TOTAL
0,1,SP,19,Superior Cursando,Solteiro,0,False,0,0.0,False,0.0,8,True,1800.0,0,0.0,1800.0
1,2,MG,23,Superior Completo,Solteiro,1,False,0,0.0,False,0.0,9,False,4800.0,1,50000.0,4800.0
2,3,SC,25,Segundo Grau Completo,Casado,0,True,1,220000.0,False,0.0,18,True,2200.0,2,30000.0,2200.0
3,4,PR,27,Superior Cursando,Casado,1,True,0,0.0,False,0.0,22,False,3900.0,0,0.0,3900.0
4,5,RJ,28,Superior Completo,Divorciado,2,False,1,370000.0,False,0.0,30,True,6100.0,1,35000.0,6100.0

In [5]:
X_treino, X_teste, y_treino, y_teste = train_test_split(preditoras, target, test_size = 0.3, random_state = 459)

In [6]:
sc = MinMaxScaler()
X_treino_normalizados = sc.fit_transform(X_treino)
X_teste_normalizados = sc.transform(X_teste)

ValueError: could not convert string to float: 'SP'

## Criar, avaliar e testar nosso modelo preditivo

In [ ]:
scaler = StandardScaler()
X_treino_normalizados = scaler.fit_transform(X_treino)
X_teste_normalizados = scaler.transform(X_teste)

modelo = LinearRegression(fit_intercept=True)
modelo.fit(X_treino_normalizados, y_treino)

In [ ]:
r2_score(y_teste, modelo.fit(X_treino_normalizados, y_treino).predict(X_teste_normalizados))

In [ ]:
UF = 2
IDADE = 42 
ESCOLARIDADE = 1
ESTADO_CIVIL = 2
QT_FILHOS = 1
CASA_PROPRIA = 1
QT_IMOVEIS = 1
VL_IMOVEIS = 300000
OUTRA_RENDA = 1
OUTRA_RENDA_VALOR = 2000 
TEMPO_ULTIMO_EMPREGO_MESES = 18 
TRABALHANDO_ATUALMENTE = 1
ULTIMO_SALARIO = 5400.0
QT_CARROS = 4
VALOR_TABELA_CARROS = 70000
FAIXA_ETARIA = 3

novos_dados = [UF, IDADE, ESCOLARIDADE, ESTADO_CIVIL, QT_FILHOS,CASA_PROPRIA,QT_IMOVEIS,VL_IMOVEIS,OUTRA_RENDA,
               OUTRA_RENDA_VALOR,TEMPO_ULTIMO_EMPREGO_MESES,TRABALHANDO_ATUALMENTE,ULTIMO_SALARIO,QT_CARROS,
               VALOR_TABELA_CARROS, FAIXA_ETARIA]


X = np.array(novos_dados).reshape(1, -1)
X = sc.transform(X)

print("Score de crédito previsto para esse cliente:", modelo.predict(X))